---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: nginx
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a custom configmap Index file. NGINX</h1>
    </html

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-file
          mountPath: /usr/share/nginx/html/
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "10m" 
      volumes:
      - name: nginx-index-file
        configMap:
          name: index-html-configmap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-demo
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cpu-ctr
        image: vish/stress
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        args:
        - -cpus
        - "2"


---
apiVersion: v1
kind: Service
metadata:
  labels:
     app: nginx
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
