---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: {{ .Values.namespace }}
  labels:
    app: selenium-node-chrome
spec:
  replicas: {{ .Values.image.seleniumChromeNode.replicas }}
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome
        image: "{{ .Values.image.seleniumChromeNode.repository }}:{{ .Values.image.seleniumChromeNode.tag  }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 5901
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        env:
        - name: HUB_HOST
          value: "selenium-hub-service.{{ .Values.namespace }}.svc.cluster.local"
        - name: HUB_PORT
          value: "4444"
        - name: NODE_MAX_INSTANCES
          value: "3"
        - name: NODE_MAX_SESSION
          value: "3" 
