---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: docker-registry
type: Opaque
data:
  HTPASSWD: YWRtaW46JDJ5JDA1JFFoWmJqM3ZuWnN5STVncExPaUllTk9jM3FJdE9DRjVzcms2dTJlQVBxUzN0ZFU0Uk0xNXBhCg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-configmap
  namespace: docker-registry
data:
  registry-config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: docker-registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.8.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: registry
          containerPort: 5000
          protocol: TCP 
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        volumeMounts:
        - name: storage
          mountPath: /var/lib/registry/docker
        - name: registry-vol
          mountPath: /var/lib/registry
        - name: htpasswd
          mountPath: /auth
      volumes:
      - name: storage
        emptyDir: {} 
      - name: registry-vol
        configMap:
          name: registry-configmap
          items:
          - key: registry-config.yml
            path: config.yml
      - name: htpasswd
        secret:
          secretName: registry-auth
          items:
          - key: HTPASSWD
            path: htpasswd


---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: docker-registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 30500
