---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  ROOT_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: mysql
subsets:
- addresses:
  - ip: 192.168.1.146
  ports:
  - port: 49152
- addresses:
  - ip: 192.168.1.24
  ports:
  - port: 49152
- addresses:
  - ip: 192.168.1.30
  ports:
  - port: 49152

---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: mysql
spec:
  ports:
  - port: 49152


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-glusterfsvol 
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-glusterfsvol
        glusterfs:
          endpoints: glusterfs-cluster
          path: k8s_vol1
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
