---
version: "3.8"

services:
   selenium-hub:
      image: selenium/hub:4.3
      container_name: selenium-hub
      networks:
      - selenumnet
      ports:
      - 4442:4442
      - 4443:4443    
      - 4444:4444

   chrome:
      image: selenium/node-chrome:103.0
      container_name: chrome
      shm_size: 2gb
      volumes:
      - /dev/shm:/dev/shm
      depends_on:
      - selenium-hub
      environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
      networks:
      - selenumnet
      ports:
      - 5901:5900

    
   firefox:
      image: selenium/node-firefox:102.0
      container_name: firefox
      shm_size: 2gb
      volumes:
      - /dev/shm:/dev/shm
      depends_on:
      - selenium-hub
      environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
      networks:
      - selenumnet
      ports:
      - 5902:5900


networks:
   selenumnet:
      driver: bridge
