---
apiVersion: v1
kind: Namespace
metadata:
  name: jmeter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-deployment
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      containers:
      - name: jmeter
        image: confluentinc/cp-zookeeper:7.1.2
        ports:
        - containerPort: 2181
