namespace: selenium

rancherClusterId: "c-m-dgcc9jdd"
rancherProjectId: "p-88ptj"

image:
    seleniumHub:
        repository: "selenium/hub"
        tag: "3.141.59"
        replicas: 1
    seleniumFirefoxNode:
        repository: "selenium/node-firefox-debug"
        tag: "3.141.59"
        replicas: 1
        max_instances: "2"
        max_sessions: "2"
    seleniumChromeNode:
        repository: "selenium/node-chrome-debug"
        tag: "3.141.59"
        replicas: 1
        max_instances: "2"
        max_sessions: "2"
    seleniumOperaNode:
        repository: "selenium/node-opera-debug"
        tag: "3.141.59"
        replicas: 1
        max_instances: "2"
        max_sessions: "2"
    pullPolicy: "IfNotPresent"

gatewayHub:
    gwhubhosts:
    - "selenium-hub.ucheonyekwuluje.com"

gatewayNode:
    gwNodehosts:
    - "selenium-chrome-node.ucheonyekwuluje.com"
