---
apiVersion: v1
kind: Namespace
metadata:
  name: kafkaclster


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafkaclster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: kafkaclster
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: kafkaclster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-svc.kafkaclster.svc.cluster.local:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(KAFKA_POD_IP):9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://$(KAFKA_POD_IP):9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LOG_CLEANUP_POLICY
              value: "compact"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafkaclster
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
