---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-opera
  namespace: {{ .Values.namespace }}
  labels:
    app: selenium-node-opera
spec:
  replicas: {{ .Values.image.seleniumOperaNode.replicas }}
  selector:
    matchLabels:
      app: selenium-node-opera
  template:
    metadata:
      labels:
        app: selenium-node-opera
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-opera
        image: "{{ .Values.image.seleniumOperaNode.repository }}:{{ .Values.image.seleniumOperaNode.tag  }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 4444
          protocol: TCP
        - containerPort: 5555
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        env:
        - name: HUB_HOST
          value: "selenium-hub-service.{{ .Values.namespace }}.svc.cluster.local"
        - name: HUB_PORT
          value: "4444"
        - name: NODE_MAX_INSTANCES
          value: "{{ .Values.image.seleniumOperaNode.max_instances }}"
        - name: NODE_MAX_SESSION
          value: "{{ .Values.image.seleniumOperaNode.max_sessions }}"
          

---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node-opera
  namespace: {{ .Values.namespace }}
  labels:
    name: selenium-node-opera
spec:
  selector:
    app: selenium-node-opera
    browser: opera
  ports:
    - name: nodeport
      protocol: TCP
      port: 5555
      targetPort: 5555
    - name: node-port-grid
      protocol: TCP
      port: 4444
      targetPort: 4444
