---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: {{ .Values.namespace }}
  labels:
    app: selenium-hub
spec:
  replicas: {{ .Values.image.seleniumHub.replicas }}
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: "{{ .Values.image.seleniumHub.repository }}:{{ .Values.image.seleniumHub.tag  }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 4444
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  labels:
     app: selenium-hub
  name: selenium-hub-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: selenium-hub 
  ports:
  - name: selenium-hub-http
    port: 4444
    targetPort: 4444
    protocol: TCP
  - name: selenium-node-http
    port: 5555
    targetPort: 5555
    protocol: TCP
