---
version: '3.8'

services:
  redis:
    container_name: redis-server
    hostname: redis-server
    image: library/redis:6.0.8-alpine
    restart: always
    ports:
    - "6379:6379"
    expose:
    - 6379
    volumes: 
    - redisdb:/data:rw
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  redisdb:
    driver: local
