variable "project_suffix" {}
variable "public_subnet_1_id" {}
variable "public_subnet_2_id" {}
variable "server_name" {}
variable "aws_ami" {}
variable "aws_type" {}
variable "node_count" {}
variable "security_group" {}
variable "ssh_keypair" {}
variable "vpc_id" {}
