---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: testdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: postgresdb
spec:
  replicas: 1
  selector:
      matchLabels:
        name: postgres-db
  template:
    metadata:
      labels:
        name: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Values.namespace }}-cm
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: postgres-db
spec:
  ports:
  - port: 5432
  selector:
    name: postgres-db
