---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sonarqube
  labels:
    app: postgres
data:
  POSTGRES_DB: sonar
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /data/sonarqube/postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - prod-kube-node02

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-pvc
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: sonarqube
  labels:
    app: postgres
spec:
  ports:
   - port: 5432
  selector:
   app: postgres
