---
version: "3.9"

services:
  init:
    image: bash
    privileged: true
    user: root
    volumes:
    - ./scripts/init.sh:/mnt/init.sh 
    command: ["sh", "-e", "/mnt/init.sh"]
 
  sonarqube:
    image: sonarqube:9.2.1-community
    restart: unless-stopped
    container_name: sonarqube
    depends_on:
    - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonardb
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar 
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_logs:/opt/sonarqube/logs
    - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
    - 9000:9000
    - 9092:9092
    ulimits:
      nproc: 131072
      nofile:
        soft: 655364
        hard: 655364
    networks:
    - sonar_network

  db:
    image: postgres:14
    restart: unless-stopped
    container_name: postgresdb
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonardb
    ports:
    - 5432:5432 
    volumes:
    - postgresql:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data
    networks:
    - sonar_network

networks:
  sonar_network:
    driver: bridge


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
