---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus3-sonartype

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: nexus3-server
  name: nexus3-deployment
  namespace: nexus3-sonartype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3-server
  template:
    metadata:
      labels:
        app: nexus3-server
    spec:
      containers:
      - name: nexus3-sonartype
        image: sonatype/nexus3:3.38.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/nexus-data"
          name: nexus-data
          subPath: sonatype
        ports:
        - containerPort: 8081
          protocol: TCP
      volumes:
      - name: nexus-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus3-server 
  name: nexus3-svc
  namespace: nexus3-sonartype
spec:
  ports:
  - name: nexus3
    port: 8081
    targetPort: 8081
    nodePort: 32001
  - name: registry
    port: 5000
    targetPort: 5000 
    nodePort: 32002

  selector:
    app: nexus3-server
  type: NodePort
