---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argoproj-manager
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argoproj-manager-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argo-cd
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: argoproj-manager
  apiGroup: ""
