---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-services
  namespace: argo-cd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: k8s-manifests/k8s-nginx/
    repoURL: git@github.com:uonyekwuluje/devops-labs.git
    targetRevision: main
  syncPolicy:
    automated: 
       prune: true
       selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - ApplyOutOfSyncOnly=true
